config/routes.rb
Rails.application.routes.draw do

  resources :airports, :flights

  resources :bookings, only: [:new, :create, :show]
  root 'flights#index'
end

app/models/airport.rb
class Airport < ActiveRecord::Base

	has_many :departures, class_name: "Flight", foreign_key: :start_location_id
	has_many :arrivals, class_name: "Flight", foreign_key: :destination_id


end

app/models/booking.rb
class Booking < ActiveRecord::Base
	belongs_to :flight
	has_many :passengers, through: :tickets
	has_many :tickets
	accepts_nested_attributes_for :passengers

	validates :flight, presence: true

end

app/models/flight.rb
class Flight < ActiveRecord::Base

	belongs_to :start_location, class_name: "Airport"
	belongs_to :destination, class_name: "Airport"
	has_many :bookings
	has_many :passengers, through: :bookings

	attr_accessor :num_passengers

	def departure_time_formatted
		self.departure_time.strftime("%m/%d/%Y")
	end

	def self.search(params)
		if params.has_key?(:departure_time)
			range = (params[:departure_time].to_date.beginning_of_day..params[:departure_time].to_date.end_of_day)
			result = Flight.where(departure_time: range)
			params.delete(:departure_time)
			result.where(params)
		else
			Flight.where(params)
		end
	end
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
	has_many :bookings, through: :tickets
	has_many :tickets
	has_many :flights, through: :bookings
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
	belongs_to :booking
	belongs_to :passenger
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	def new
		@booking = Booking.new
		@flight = Flight.find(params[:flight_id])
		params[:num_passengers].to_i.times do
			@booking.passengers.build
		end
	end

	def create
		@booking = Booking.new(booking_params)
		if @booking.save
			PassengerMailer.thank_you_email(@booking).deliver_later
			flash[:success] = "Successfully created"
			redirect_to @booking
		else
			flash.now[:danger] = "Error"
			render 'new'
		end
	end

	def show
		@booking = Booking.find(params[:id])
	end


	private

		def booking_params
			params.require(:booking).permit(:id, :flight_id, passengers_attributes: [:id, :name, :email])
		end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
	def index
		@flights = Flight.all
		@start_locations = Airport.all.map { |a| [a.code, a.id]}
		@destinations = Airport.all.map { |a| [a.code, a.id]}
		@departure_times = @flights.all.order("departure_time ASC").uniq
		@num_passengers = (1..4).map { |n| [n,n] }
		@booking = Booking.new

		conditions = {}
		if params.has_key?(:search)
			conditions[:start_location] = params[:search][:start_location] unless params[:search][:start_location].blank?
			conditions[:destination] = params[:search][:destination] unless params[:search][:destination].blank?
			conditions[:departure_time] = params[:search][:departure_time] unless params[:search][:departure_time].blank?
			
			@results = Flight.search(conditions)
		end
	end

	private

		def search_params
			params.require(:search).permit(:start_location, :destination, :departure_time, :num_passengers)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/new.html.erb
<h1>Book your flight</h1>
<%= form_for @booking do |f| %>
	<p>Departure: <%= @flight.departure_time %></p>
	<p>Flight No.<%= @flight.id %></p>
	<p>From: <%= @flight.start_location.code %></p>
	<p>To: <%= @flight.destination.code %></p>
	<%= f.fields_for :passengers do |passenger_form| %>
		<p>
			<%= passenger_form.label :name %>
			<%= passenger_form.text_field :name %>
			<%= passenger_form.label :email %>
			<%= passenger_form.email_field :email %>
		</p>
	<% end %>	
	<%= f.hidden_field :flight_id, value: @flight.id %>	
	<%= f.submit "Submit" %>
<% end %>

app/views/bookings/show.html.erb
Flight From: <%= @booking.flight.start_location.code %>
to <%= @booking.flight.destination.code %>
<%= @booking.flight.departure_time %>

<% @booking.passengers.each do |passenger| %>
	<p>
		<%= passenger.name %>
		<%= passenger.email %>
	</p>
<% end %>

app/views/flights/index.html.erb
<ul>
	<%= form_tag flights_path, method: :get do %>
		<%= fields_for :search do |f| %>
			<li>
				<%= f.label "FROM" %>
				<%= f.select(:start_location, options_for_select(@start_locations), include_blank: true)  %>
			</li>
			<li>
				<%= f.label "TO" %>
				<%= f.select(:destination, @destinations, include_blank: true) %>
			</li>
			<li>
				<%= f.label "Passengers" %>
				<%= f.select(:num_passengers, @num_passengers ) %>
			</li>
			<li>
				<%= f.select("departure_time", options_from_collection_for_select(@departure_times, :departure_time, :departure_time_formatted), include_blank: true) %>
			</li>
			<li>
				<%= f.submit "Submit", name: nil %>
			</li>
		<% end %>
	<% end %>
</ul>

<% if @results %>
	<ul>
	<%= form_tag new_booking_path, method: :get do %>
		<%= hidden_field_tag :num_passengers, params[:search][:num_passengers] %>
		<% @results.each do |result| %>
			<h1>Flight</h1>
			<%= radio_button_tag :flight_id, result.id %>
			<ul>
				<li>From: <%=  result.start_location.code %></li>
				<li>To: <%= result.destination.code %></li>
				<li>On: <%= result.departure_time %></li>
				<li>Duration: <%= distance_of_time_in_words(result.flight_duration_in_seconds) %></li>
			</ul>
		<% end %>
		<%= submit_tag "Select Flight", name: nil %>
	<% end %>		
	</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TopFlightBooker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= debug(params) if Rails.env.development? %>
</body>
</html>